---
title: "eds-212-day-2"
author: "Desik Somasundaram"
date: "8/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(palmerpenguins)

```

## First Order Univariate Derivatives

# A.

```{r}

fx <- expression(x^2)

df_dx <- D(expr = fx,name ="x")

x <- 3

eval(df_dx)

```

# B.

```{r}

pa <- expression((2*(((3*a) + 2 )^4)) - 5)

p_da <- D(expr = pa,name ="a")

a <- 1.2

eval(p_da)

```

# C.

```{r}

gt <- expression((-4*t)/((t^2 + 1)^3))

g_dt <- D(expr = gt,name ="t")

t <- 0

eval(g_dt)

```
# Higher order univariate derivatives:

```{r}
gz <- expression(4.6 - (1.9*(z^3)))

g_dz <- D(expr = gz,name ="z")

g_d2z <- D(expr = g_dz,name ="z")

```


# Partial Derivatives 

```{r}
fxyz <- expression((2*(x^2)*y) - (3*x) + 1 + (4*(z^4)*x))

f_dx <- D(expr = fxyz,name ="x")

f_dy <- D(expr = fxyz,name ="y")

f_dz <- D(expr = fxyz,name ="z")

```


```{r}
fx_section4 <- function(x) {(2.4*(exp(-0.05*x)) * sin(x))}


ggplot(data.frame(x = c(-0.5,0.5)), aes(x = x)) + stat_function(fun = fx_section4)

ggplot(data = NULL) + stat_function(fun = fx_section4) + xlim(-0.5,0.5)

```

### Basic ggplot scatterplot of body mass (y) and flipper length (x)

```{r}

ggplot(data = penguins, aes(x = bill_length_mm, y = bill_depth_mm)) + 
  geom_point(aes(color = species)) + 
  scale_color_manual(values = c("purple", "green","red")) +
  labs(x = "Bill length (mm)", y = "Bill depth (mm)", 
       title = "Palmer penguins bill size measurements", 
       caption = "Data   collected by KB Gorman et al. at Palmer Station", color = "Species") +
  theme_light()

```

